#!/bin/bash
seq -w 30 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc1/mprime/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc1/mprime/p{}.pddl -i 8 '>>' GreedyMprime.txt
printf "IPC1 MPrime finished"
seq -w 30 | parallel -k --timeout 600 -j1 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc1/logistics/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc1/logistics/p{}.pddl -i 8 '>>' GreedyLogistics.txt
printf "IPC1 Logistics finished"
seq -w 30 | parallel -k --timeout 600 -j1 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc1/mystery/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc1/mystery/p{}.pddl -i 8 '>>' GreedyMystery.txt
printf "IPC1 Mystery finished"
seq -w 20 | parallel -k --timeout 600 -j1 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc1/gripper/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc1/gripper/p{}.pddl -i 8 '>>' GreedyGripper.txt
printf "IPC1 Gripper finished"
seq -w 30 | parallel -k --timeout 600 -j1 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc1/movie/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc1/movie/p{}.pddl -i 8 '>>' GreedyMovie.txt
printf "IPC1 Movie finished"
seq -w 60 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc2/freecell/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc2/freecell/p{}.pddl -i 8 '>>' GreedyFreecell.txt
printf "IPC2 Freecell finished "
seq -w 99 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc2/elevator/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc2/elevator/p{}.pddl -i 8 '>>' GreedyElevator.txt
printf "IPC2 Elevator finished "
seq -w 35 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc2/blocksworld/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc2/blocksworld/p{}.pddl -i 8 '>>' GreedyBlocksworld.txt
printf "IPC2 Blocksworld finished "
seq -w 99 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc2/schedule/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc2/schedule/p{}.pddl -i 8 '>>' GreedySchedule.txt
printf "IPC2 Schedule finished "
printf "IPC2 has finished"
seq -w 22 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc3/depots/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc3/depots/p{}.pddl -i 8 '>>' GreedyDepots.txt
printf "IPC3 Depots finished "
seq -w 20 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc3/driverlog/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc3/driverlog/p{}.pddl -i 8 '>>' GreedyDriverlog.txt
printf "IPC3 Depots finished "
seq -w 20 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc3/rover/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc3/rover/p{}.pddl -i 8 '>>' GreedyRover.txt
printf "IPC3 Rover finished "
seq -w 20 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc3/satellite/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc3/satellite/p{}.pddl -i 8 '>>' GreedySatellite.txt
printf "IPC3 Satellite finished "
seq -w 20 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc3/zenotravel/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc3/zenotravel/p{}.pddl -i 8 '>>' GreedyZenotravel.txt
printf "IPC3 Zeno finished "
printf "IPC3 has finished"
seq -w 50 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc4/pipesworld/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc4/pipesworld/p{}.pddl -i 8 '>>' GreedyPipesworld.txt
printf "IPC4 Pipesworld finished "
seq -w 50 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc4/airport/p{}-domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc4/airport/p{}.pddl -i 8 '>>' GreedyAirport.txt 
printf "IPC4 Airport finished "
seq -w 14 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc4/optical-telegraph/p{}-domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc4/optical-telegraph/p{}.pddl -i 8 '>>' GreedyOpticalTelegraph.txt 
printf "IPC4 Optical Telegraph finished "
seq -w 29 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc4/philosophers/p{}-domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc4/philosophers/p{}.pddl -i 8 '>>' GreedyPhilosophers.txt
printf "IPC4 Philosophers finished "
seq -w 50 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc4/psr/p{}-domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc4/psr/p{}.pddl -i 8 '>>' GreedyPsr.txt
printf "IPC4 Psr finished "
printf "IPC4 has finished"
seq -w 30 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc5/storage/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc5/storage/p{}.pddl -i 8 '>>' GreedyStorage.txt
printf "IPC5 Storage finished "
seq -w 30 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc5/openstacks/p{}-domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc5/openstacks/p{}.pddl -i 8 '>>' GreedyOpenstacks.txt
printf "IPC5 Openstack finished "
seq -w 30 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc5/pathways/p{}-domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc5/pathways/p{}.pddl -i 8 '>>' GreedyPathways.txt
printf "IPC5 Pathways finished "
seq -w 30 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc5/tpp/p{}-domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc5/tpp/p{}.pddl -i 8 '>>' GreedyTpp.txt
printf "IPC5 Tpp finished "
seq -w 30 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc5/truck/p{}-domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc5/truck/p{}.pddl -i 8 '>>' GreedyTruck.txt
printf "IPC5 Truck finished "
printf "IPC5 has finished"
seq -w 30 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc6/pegsol/p{}-domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc6/pegsol/p{}.pddl -i 8 '>>' GreedyPegsol.txt
printf "IPC6 Pegsol finished "
seq -w 30 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc6/sokoban/p{}-domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc6/sokoban/p{}.pddl -i 8 '>>' GreedySokoban.txt
printf "IPC6 Sokoban finished "
seq -w 30 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc6/transport/p{}-domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc6/transport/p{}.pddl -i 8 '>>' GreedyTransport.txt
printf "IPC6 Transport finished "
printf "IPC6 has finished"
seq -w 20 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc7/nomystery/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc7/nomystery/p{}.pddl -i 8 '>>' GreedyNomystery.txt
printf "IPC7 Nomystery finished "
seq -w 20 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc7/barman/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc7/barman/p{}.pddl -i 8 '>>' GreedyBarman.txt
printf "IPC7 Barman finished " 
seq -w 20 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc7/parking/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc7/parking/p{}.pddl -i 8 '>>' GreedyParking.txt
printf "IPC7 Parking finished "
printf "IPC7 has finished"
seq -w 20 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc8/childsnack/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc8/childsnack/p{}.pddl -i 8 '>>' GreedyChildsnack.txt
printf "IPC8 Childsnack finished "
seq -w 20 | parallel -k --timeout 600 -j6 java -javaagent:build/libs/pddl4j-3.1.0.jar -server -Xms8048m -Xmx8048m fr.uga.pddl4j.planners.hsp.HSP -o pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc8/thoughtful/domain.pddl -f pddl/benchmarks_STRIPS/benchmarks_STRIPS/ipc8/thoughtful/p{}.pddl -i 8 '>>' GreedyThoughtful.txt
printf "IPC8 Thoughtful finished "
printf "IPC8 has finished"
printf "Tasks have all finished"
